### ISSUE TITLE
Using .vbp file in Python

### ISSUE THREAD

**Issue by pierrbt** [fdabrandao/vpsolver#12]
Hello,
I'm trying to use VPSolver with the Python API, I found out that the result of this script : 
```python
from pyvpsolver.solvers import vbpsolver

W = (5180, 2)
w = [(1120,1), (1250,1), (520,1), (1066,1), (1000,1), (1150,1)]
b = [9, 5, 91, 18, 11, 64]

# Solve a vector packing instance:
solution = vbpsolver.solve(
    W, w, b, script="vpsolver_glpk.sh", verbose=False
)
# Print the solution:
vbpsolver.print_solution(solution)
```
was not the same as the result sent by the webapp : 
![image](https://user-images.githubusercontent.com/83456236/213931123-553898ff-4138-4a49-900e-e9b8ef531bbf.png)

I think it is from the fact that in Python we need to add a second parameter to the W variable. If you can explane that to me.
And secondly i would like to know how can we use vbp file directly in Python, in this kind of format : 
```
1
5180
6
1120 9
1250 5
520 91
1066 18
1000 11
1150 64
```
Thank you for your help.

**Comment by pierrbt** [comment]
After using the script, I guess it is the maximum number of differents sizes in a single row ?

**Comment by fdabrandao** [comment]
The example you found in python is for a instance with two dimensions and in that particular case the second dimension is cardinality. On the web app you can have the same result if you add the second dimension. Without that dimension patterns with more than two items are allowed.

```
2
5180 2
6
1120 1 9
1250 1 5
520 1 91
1066 1 18
1000 1 11
1150 1 64
```
