### ISSUE TITLE
Getting signal received 1 by vpsolver on MVP instance

### ISSUE THREAD

**Issue by S1LV3RJ1NX** [fdabrandao/vpsolver#6]
I am getting the following output on running MVP solver for a large sample. It takes more than 3-4 hours for graph compression and finally gives the signal 1 error. How to solve it? I am using gurobi solver. Same is the issue with glpk solver.
```
>>> vbp2afg...
VPSolver 3.1.3, Copyright (C) 2013-2016, Filipe Brandao
Build (method = -3)
signal received: 1
```

**Comment by S1LV3RJ1NX** [comment]
My machine has 64G of memory, I didn’t see it getting exceeded at any
point. Another thing I saw was the afg process was still running and taking
99% of the cpu, but python process had ended after receiving signal 1.

Nonetheless, can you please show how to use heuristic when patterns are
long?
Thank you.

**Comment by fdabrandao** [comment]
The signal 1 is SIGHUP (https://en.wikipedia.org/wiki/SIGHUP) which should be sent if the terminal was closed for some reason. Nevertheless, even if afg is still running, the model after so much time is likely be huge and impossible to solve. The graph generation part is generally quite fast compared to the total solve time.

In terms of heuristics for vector packing, see for instance https://www.microsoft.com/en-us/research/wp-content/uploads/2011/01/VBPackingESA11.pdf. A simple heuristic like First-Fit-Decreasing (https://en.wikipedia.org/wiki/First-fit-decreasing_bin_packing) should provide good results when patterns are long.

**Comment by S1LV3RJ1NX** [comment]
Thanks, I'll check it out. Is there any solver for FFD Bin Packing that
would really help.
