### ISSUE TITLE
VPSolver works faster in virtual machine than a bare metal server

### ISSUE THREAD

**Issue by saswat0** [fdabrandao/vpsolver#7]
I tried serving the solver via a flask application to do some benchmarking as this is a CPU-intensive job. Here's my flask snippet:

```
import uuid

from werkzeug.utils import secure_filename
from flask import Flask, request, jsonify, abort

from pyvpsolver import VPSolver, MVP

app = Flask(__name__)

@app.route('/bins', methods=['POST'])
def allocate_bins():
    tmpfile = f'temp/{str(uuid.uuid1())}'

    input_ = request.files['input']
    filename = secure_filename(input_.filename)
    input_.save(tmpfile + '_' + filename)

    instance = MVP.from_file(tmpfile + '_' + filename, verbose=False)
    out, solution = VPSolver.script("vpsolver_glpk.sh", instance, verbose=False)
    print(f"Bins: {solution[0]}")

    try:
        return jsonify({"bins": solution[0]}), 200
    except Exception as e:
        abort(404)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5005)
```

The peculiar thing about this exercise is that for some MVP files, it takes a long time (as long as 20-30 minutes) to compute in bare metal, whereas executes almost instantaneously (in 0.2-0.5s) in virtual machines. Is there any explanation for this behaviour?

When I keep the MVP file constant, the CPU is 100% utilised at 30 concurrent users in the case of bare metal, whereas it takes around 40 users to achieve the same CPU utilisation virtual machine. Isn't this a bit counterproductive? If anything, a VM should take longer to process a job than it's bare metal counterpart

**Comment by fdabrandao** [comment]
Could you please check the outputs from GLPK? A small difference in the GLPK version or system (e..g, different operating system) may take the solver through a completely different search path and that can affect performance substantially. The output from GLPK should show more details about what is happening.

**Comment by saswat0** [comment]
Yes. That was the problem indeed 🤦 
Thanks a lot for the prompt resolution!
